Navbar
uwblueprint/website-v2 pull request #2
Opened 2021-02-23 03:06 UTC by ChinemeremChigbo

what it's doing
why I did it
the changes i made

### Description

- Added NavBar with ability to allow for easy navigation of site pages
- Gave the Navbar dynamic styling so that it appears different in desktop vs mobile
- Created a global style file

### Test Plan
- [ ] Ensure that clicking on NavBar links changes pages
- [ ] Make the screen size smaller or select a phone as your viewing mode (Ctrl + Shift + M if on Chrome and Windows)
- [ ] Ensure that the sizing changes dynamically and the links still work as intended

2021-02-28 00:13 UTC, peiyaaao commented on src/components/layout/Navbar.tsx
> +  const handleClick = () => (clicked ? setClicked(false) : setClicked(true));
`const handleClick = () => (setClicked(!clicked)`

2021-02-28 00:50 UTC, peiyaaao commented on src/styles.scss
> +@import "components/layout/Navbar.scss";
Can we import the styles for the navbar locally in the navbar component as opposed to globally? Ideally the navbar styles should not be accessible by any other component/style file in the application.

2021-02-28 01:24 UTC, peiyaaao commented on src/components/layout/Navbar.scss
> +  &__logo {
Can we remove the underscores? See the below comment about importing the navbar style locally instead of importing it into the styles file globally.

2021-02-28 01:28 UTC, peiyaaao commented on src/components/layout/Navbar.tsx
> +const useStyles = makeStyles({
Is it possible for us to style material UI components by supplying classnames instead? https://material-ui.com/guides/interoperability/#global-css See basic css. Let me know if that doesn't work we might need to use css modules. Basically would need to move that style block into the scss file and access the class name from this component.

2021-02-28 01:34 UTC, peiyaaao commented on .prettierrc.json
> +  "endOfLine": "auto",
Shouldn't be here. Line ending should default to "LF" for Linux based systems. I know this will cause issues on windows machines, but if you change your text editor to type using "LF' endings.

2021-02-28 01:37 UTC, peiyaaao commented on package.json
> +    "@material-ui/core": "^4.11.3",
Couldn't comment on the package lock, but were we not able to import these dependencies using yarn? Ideally we only use one dependency manager, so we shouldn't have a package-lock, only the yarn lock.

2021-02-28 01:40 UTC, peiyaaao commented on src/components/layout/Navbar.tsx
> +            {clicked ? (
Not sure if you need the div, but you could also do `{ clicked && <...> }` if you're just trying to show and hide the div

2021-02-28 01:43 UTC, peiyaaao commented on src/components/about/About.tsx
> +      <br></br>
nit: (nit pick - basically a suggestion) do we need the break?

2021-02-28 01:44 UTC, peiyaaao requested changes
Good job guys! Just needs a few changes. If you guys are having trouble implementing the style changes / or my suggestions don't work, comment back where I commented and let me know!

2021-03-06 20:17 UTC, ChinemeremChigbo commented on src/components/about/About.tsx
> +      <br></br>
Not really? It was just there so the header wasn't too high up on the page

2021-03-08 03:45 UTC, peiyaaao approved these changes

2021-03-08 03:53 UTC, merged