Navbar + Button Component
uwblueprint/website-v2 pull request #9
Opened 2021-03-16 10:40 UTC by ChinemeremChigbo

# Description

- Added custom button component
- Added global design style colours and properties
- Added mobile dropdown overlay
- Added new mixin breakpoints for ease of use
- Added SVG components for dropdown animation
- Styled the mobile and desktop navbar and added interactivity

# Screenshots

Desktop:
![image](https://user-images.githubusercontent.com/24593519/111285703-cad10d80-8617-11eb-8190-5c622d0ffa86.png)

Mobile:
![image](https://user-images.githubusercontent.com/24593519/111295019-4d11ff80-8621-11eb-956b-bd7dfd3e5a57.png)

# Test Plan

- [ ] Install the required dependencies and start yarn
- [ ] Ensure that the Navbar Links work as intended (animated on hover, take you to appropriate website, mouse turns to cursor at right spots etc.)
- [ ] Reduce you browser screen size until mobile device mode is activated
- [ ] Ensure that the Links continue to behave as intended, with the navbar disappearing after selecting a link and with the overlay closing if one clicks away.
- [ ] Now, using Dev tools (Right Click>Inspect Element or F12 on Windows) toggle the device toolbar (Ctrl/Cmd + Shift + M).
- [ ] Experiment with various mobile/desktop sizes and shapes and ensure that functionality persists

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Any dependent changes have been merged and published in downstream modules

2021-03-28 01:03 UTC, peiyaaao requested changes
Hey! Sorry this took me so long to review.
Some of the changes are file structure related, and slightly code organization related.

2021-03-28 01:03 UTC, peiyaaao commented on src/components/svgs/SVGs.tsx
> +// SVGs for the Blueprint logo and Name. Adding the SVGs in a tsx file allows one to edit the properties more easily than in the svg format (using the adjacent scss file).
Instead of creating an svgs folder can we move this to the common folder and name it BlueprintLogo.tsx?

2021-03-28 01:33 UTC, ChinemeremChigbo commented on src/components/about/About.scss
> +  color: $C00
It changes the font colour for specifically the about us page
![image](https://user-images.githubusercontent.com/24593519/112739648-ffac6100-8f43-11eb-81a2-97ff1b764d5d.png)

2021-03-28 01:40 UTC, ChinemeremChigbo commented on src/components/about/About.tsx
> +  return (
Yeah, kinda. It's just to have the placeholder text be align from the navbar so that things can look alright. I expect it to be overwritten when people add the actual individual pages.
![image](https://user-images.githubusercontent.com/24593519/112739737-af81ce80-8f44-11eb-93d3-7a92c7bf2190.png)

2021-03-29 23:58 UTC, ChinemeremChigbo commented on src/components/App.tsx
> +        <Route path="/about">
Since all the pages have unique names the only one that technically _needs_ to be exact is the first "/". And I got rid of them since I didn't want to be redundant. However, for the sake of consistency and future proofing I think it might be better to bring them back.

https://stackoverflow.com/questions/49162311/react-difference-between-route-exact-path-and-route-path#:~:text=If%20you%20want%20to%20use,exact%20for%20the%20%2Ffunctions%20route.&text=When%20true%2C%20will%20only%20match%20if%20the%20path%20matches%20the%20location.

2021-04-12 21:27 UTC, peiyaaao approved these changes

2021-04-12 23:22 UTC, merged